### ISSUE TITLE
This is new issue for me

### ISSUE THREAD

**Issue by AymenChikeb** [Aymen-Chikeb/Aymen-Text#4]
Just test issue for your repository

[This is a link](https://github.com/Aymen-Chikeb/Aymen-Text/blob/master/Colors.txt) and **this is bold**.

<img width="1047" alt="Capture d’écran 2020-01-07 à 10 26 40" src="https://user-images.githubusercontent.com/43686102/71884241-35dfa400-3138-11ea-8036-a90d447e5d09.png">

**Comment by Aymen-Chikeb** [comment]
Thanks....
